import { MigrationInterface, QueryRunner } from "typeorm";

export class Migrations1761510975115 implements MigrationInterface {
    name = 'Migrations1761510975115'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "user" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "createdById" uuid, "createdByName" character varying, "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedById" uuid, "updatedByName" character varying, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "username" character varying(80) NOT NULL, "email" character varying(150), "displayName" character varying(150) NOT NULL, "authSource" character varying(10) NOT NULL DEFAULT 'local', "externalId" character varying, "passwordHash" character varying, "isActive" boolean NOT NULL DEFAULT true, "lastLoginAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_78a916df40e02a9deb1c4b75ed" ON "user" ("username") `);
        await queryRunner.query(`CREATE TABLE "membership" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "createdById" uuid, "createdByName" character varying, "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedById" uuid, "updatedByName" character varying, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "groupId" uuid NOT NULL, CONSTRAINT "PK_83c1afebef3059472e7c37e8de8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8bc1674087575acecf0a648fc9" ON "membership" ("groupId") `);
        await queryRunner.query(`CREATE INDEX "IDX_eef2d9d9c70cd13bed868afedf" ON "membership" ("userId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_9c7d697a4844cf8b931988b24f" ON "membership" ("userId", "groupId") `);
        await queryRunner.query(`CREATE TABLE "business_line" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "createdById" uuid, "createdByName" character varying, "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedById" uuid, "updatedByName" character varying, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "key" character varying NOT NULL, "name" character varying NOT NULL, "description" character varying, "active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_b3f4256a5b0584433a296cf0dc2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_f81f7f3398bd7c979dd3b59deb" ON "business_line" ("key") `);
        await queryRunner.query(`CREATE TABLE "group" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "createdById" uuid, "createdByName" character varying, "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedById" uuid, "updatedByName" character varying, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "key" character varying(80) NOT NULL, "name" character varying(120) NOT NULL, "description" character varying, "businessLineId" uuid NOT NULL, CONSTRAINT "PK_256aa0fda9b1de1a73ee0b7106b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c4ba7ec4945931d3ffab972448" ON "group" ("businessLineId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_b2177905daa1bf150e743072d3" ON "group" ("key") `);
        await queryRunner.query(`CREATE TABLE "role" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "createdById" uuid, "createdByName" character varying, "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedById" uuid, "updatedByName" character varying, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "key" character varying NOT NULL, "name" character varying NOT NULL, "description" character varying, CONSTRAINT "PK_b36bcfe02fc8de3c57a8b2391c2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_128d7c8c9af53479d0b9e00eb5" ON "role" ("key") `);
        await queryRunner.query(`CREATE TABLE "user_role" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "createdById" uuid, "createdByName" character varying, "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedById" uuid, "updatedByName" character varying, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "roleId" uuid NOT NULL, CONSTRAINT "PK_fb2e442d14add3cefbdf33c4561" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_dba55ed826ef26b5b22bd39409" ON "user_role" ("roleId") `);
        await queryRunner.query(`CREATE INDEX "IDX_ab40a6f0cd7d3ebfcce082131f" ON "user_role" ("userId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_7b4e17a669299579dfa55a3fc3" ON "user_role" ("userId", "roleId") `);
        await queryRunner.query(`CREATE TABLE "group_role" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "createdById" uuid, "createdByName" character varying, "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedById" uuid, "updatedByName" character varying, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "groupId" uuid NOT NULL, "roleId" uuid NOT NULL, CONSTRAINT "PK_0fd3365b65e6121a0ef0cb7cb6e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e3fadd3be8dac5f5dcfe44551b" ON "group_role" ("roleId") `);
        await queryRunner.query(`CREATE INDEX "IDX_5f5e3b95cbdf0582623d98adf1" ON "group_role" ("groupId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_4ae7c04176fcfe3a6aef3f368b" ON "group_role" ("groupId", "roleId") `);
        await queryRunner.query(`CREATE TABLE "permission" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "createdById" uuid, "createdByName" character varying, "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedById" uuid, "updatedByName" character varying, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "key" character varying NOT NULL, "subject" character varying NOT NULL, "action" character varying NOT NULL, "conditions" jsonb, "description" character varying, CONSTRAINT "PK_3b8b97af9d9d8807e41e6f48362" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_20ff45fefbd3a7c04d2572c3bb" ON "permission" ("key") `);
        await queryRunner.query(`CREATE TABLE "role_permission" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "createdById" uuid, "createdByName" character varying, "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedById" uuid, "updatedByName" character varying, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "roleId" uuid NOT NULL, "permissionId" uuid NOT NULL, CONSTRAINT "PK_96c8f1fd25538d3692024115b47" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_72e80be86cab0e93e67ed1a7a9" ON "role_permission" ("permissionId") `);
        await queryRunner.query(`CREATE INDEX "IDX_e3130a39c1e4a740d044e68573" ON "role_permission" ("roleId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_b42bbacb8402c353df82243254" ON "role_permission" ("roleId", "permissionId") `);
        await queryRunner.query(`CREATE TABLE "user_permission" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "createdById" uuid, "createdByName" character varying, "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedById" uuid, "updatedByName" character varying, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "permissionId" uuid NOT NULL, CONSTRAINT "PK_a7326749e773c740a7104634a77" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a592f2df24c9d464afd71401ff" ON "user_permission" ("permissionId") `);
        await queryRunner.query(`CREATE INDEX "IDX_deb59c09715314aed1866e18a8" ON "user_permission" ("userId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_1cf6c7f47d0655afa389e1bd59" ON "user_permission" ("userId", "permissionId") `);
        await queryRunner.query(`CREATE TABLE "case" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "createdById" uuid, "createdByName" character varying, "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedById" uuid, "updatedByName" character varying, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "number" character varying(30) NOT NULL, "title" character varying(200) NOT NULL, "description" text, "status" character varying(20) NOT NULL DEFAULT 'New', "priority" character varying(20) NOT NULL DEFAULT 'Medium', "requesterId" uuid, "assigneeId" uuid, "assignmentGroupId" uuid, "businessLineId" uuid NOT NULL, CONSTRAINT "PK_a1b20a2aef6fc438389d2c4aca0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6419fb53a5bec2b9f3722dabff" ON "case" ("assignmentGroupId") `);
        await queryRunner.query(`CREATE INDEX "IDX_9973cb8611f550ca336bdad4ac" ON "case" ("businessLineId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_8cf7d3e75b7dd1eced77de0f14" ON "case" ("number") `);
        await queryRunner.query(`CREATE TABLE "case_comment" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "createdById" uuid, "createdByName" character varying, "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedById" uuid, "updatedByName" character varying, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "caseId" uuid NOT NULL, "body" text NOT NULL, CONSTRAINT "PK_cf3fac04fffd4b72988cec36ca8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2d415c0c1a476a32e1958e1738" ON "case_comment" ("caseId", "createdAt") `);
        await queryRunner.query(`CREATE TABLE "case_link" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "caseId" uuid NOT NULL, "targetCaseId" uuid NOT NULL, "type" character varying(30) NOT NULL, CONSTRAINT "PK_e80e18102707048fbbd0bdbc7f7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d398b499b3bd5ca7a3e0c8d392" ON "case_link" ("targetCaseId") `);
        await queryRunner.query(`CREATE INDEX "IDX_1a773d805281cba5adb9dccaae" ON "case_link" ("caseId") `);
        await queryRunner.query(`CREATE TABLE "case_attachment" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "caseId" uuid NOT NULL, "filename" character varying NOT NULL, "originalName" character varying NOT NULL, "mimeType" character varying NOT NULL, "size" integer NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "createdById" character varying NOT NULL, "createdByName" character varying NOT NULL, "storagePath" character varying NOT NULL, CONSTRAINT "PK_986ce92847042b75efad5e39601" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f3e06f2721e46eea00824b311d" ON "case_attachment" ("caseId") `);
        await queryRunner.query(`CREATE TABLE "refresh_token" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "token" character varying(500) NOT NULL, "expiresAt" TIMESTAMP WITH TIME ZONE NOT NULL, "isRevoked" boolean NOT NULL DEFAULT false, "userAgent" character varying(300), "ipAddress" character varying(45), "lastUsedAt" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_b575dd3c21fb0831013c909e7fe" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_aa5d23e946f1e4dc31a57ee1a5" ON "refresh_token" ("userId", "isRevoked") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_c31d0a2f38e6e99110df62ab0a" ON "refresh_token" ("token") `);
        await queryRunner.query(`CREATE TABLE "token_blacklist" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "jti" character varying(100) NOT NULL, "userId" uuid NOT NULL, "expiresAt" TIMESTAMP WITH TIME ZONE NOT NULL, "reason" character varying(50) NOT NULL DEFAULT 'logout', "revokedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_3e37528d03f0bd5335874afa48d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1cebed586d3a7c46f3f9b76cf1" ON "token_blacklist" ("expiresAt") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_73e5965ffdbd4a9f2de7c93043" ON "token_blacklist" ("jti") `);
        await queryRunner.query(`CREATE TABLE "sla_target" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "createdById" uuid, "createdByName" character varying, "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedById" uuid, "updatedByName" character varying, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "key" character varying NOT NULL, "name" character varying NOT NULL, "goalMs" integer NOT NULL, "referenceModule" "public"."sla_target_referencemodule_enum" NOT NULL, "rules" jsonb NOT NULL, "businessLineId" uuid NOT NULL, "isActive" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_563f8482a2eefdc3f6c7ff55200" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7f6aa7deacb0e09d51f147c27f" ON "sla_target" ("businessLineId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_735b920a4e967f99beb36d8c0d" ON "sla_target" ("key", "businessLineId") `);
        await queryRunner.query(`CREATE TABLE "sla_timer" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "caseId" uuid NOT NULL, "targetId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "startedAt" TIMESTAMP WITH TIME ZONE NOT NULL, "stoppedAt" TIMESTAMP WITH TIME ZONE, "breachedAt" TIMESTAMP WITH TIME ZONE, "lastTickAt" TIMESTAMP WITH TIME ZONE, "remainingMs" integer NOT NULL, "status" character varying NOT NULL DEFAULT 'Running', "pausedAt" TIMESTAMP WITH TIME ZONE, "resumedAt" TIMESTAMP WITH TIME ZONE, "totalPausedMs" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_fb892fc33395d5096bc23c88057" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_19c74fad2a0ac4ec41253baa03" ON "sla_timer" ("caseId") `);
        await queryRunner.query(`CREATE INDEX "IDX_d21e45bed4b3906ecf59fc6aef" ON "sla_timer" ("targetId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_f3e3ceaee9e1f40d91736b24c1" ON "sla_timer" ("caseId", "targetId") `);
        await queryRunner.query(`CREATE TABLE "email_channel" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "createdById" uuid, "createdByName" character varying, "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedById" uuid, "updatedByName" character varying, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "businessLineId" uuid NOT NULL, "kind" character varying NOT NULL, "name" character varying NOT NULL, "fromAddress" character varying NOT NULL, "replyTo" character varying, "host" character varying NOT NULL, "port" integer NOT NULL, "secure" boolean NOT NULL DEFAULT false, "username" character varying, "password" character varying, "oauthType" character varying, "oauthClientId" character varying, "oauthClientSecret" character varying, "oauthTenant" character varying, "oauthRefreshToken" character varying, "enabled" boolean NOT NULL DEFAULT true, "isDefault" boolean NOT NULL DEFAULT false, "lastStatus" character varying, "lastError" character varying, CONSTRAINT "PK_80c1038fee35aace2774e928d51" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_16b07ef60f6bb9b05188518c1e" ON "email_channel" ("businessLineId") `);
        await queryRunner.query(`CREATE INDEX "IDX_c110b35ab63da1889e49127a9a" ON "email_channel" ("businessLineId", "kind", "isDefault") `);
        await queryRunner.query(`CREATE TABLE "email_inbound_state" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "channelId" uuid NOT NULL, "lastUid" character varying, "lastUidValidity" character varying, "lastMsgId" character varying, "lastPolledAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_467854020a9483fc0052957dd2c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_74b7832881f05a5b8376146db7" ON "email_inbound_state" ("channelId") `);
        await queryRunner.query(`CREATE TABLE "email_message" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "channelId" uuid NOT NULL, "caseId" uuid, "messageId" character varying NOT NULL, "inReplyTo" character varying, "references" jsonb, "fromAddr" character varying, "toAddrs" jsonb, "subject" character varying, "textBody" text, "htmlBody" text, "direction" character varying NOT NULL DEFAULT 'inbound', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_9fe3a0a31f2ffe66dd976851792" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_907f61c9fef57870dd592b8f9b" ON "email_message" ("channelId") `);
        await queryRunner.query(`CREATE INDEX "IDX_8322240cf857228a7f70746ad8" ON "email_message" ("caseId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_a73d83b3021f6d56a57965adf3" ON "email_message" ("messageId") `);
        await queryRunner.query(`CREATE TABLE "email_routing_rule" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "businessLineId" uuid NOT NULL, "channelId" uuid NOT NULL, "toContains" character varying, "subjectIncludes" character varying, "fromDomain" character varying, "assignGroupId" uuid NOT NULL, "templateId" uuid, "priority" character varying, "label" character varying, CONSTRAINT "PK_64b0bb7010964b9149ea8bd04ef" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e67071c18c96a0be0d8d1af826" ON "email_routing_rule" ("businessLineId") `);
        await queryRunner.query(`CREATE TABLE "notification_template" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "createdById" uuid, "createdByName" character varying, "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedById" uuid, "updatedByName" character varying, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "businessLineId" uuid NOT NULL, "key" character varying NOT NULL, "subject" character varying NOT NULL, "bodyHtml" text NOT NULL, CONSTRAINT "PK_d2a6ef77141a01b8ac31f514cfc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_ffdbbd32062ba09e2aebe72d00" ON "notification_template" ("businessLineId", "key") `);
        await queryRunner.query(`CREATE TABLE "audit_event" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" character varying NOT NULL, "aggregateType" character varying NOT NULL, "aggregateId" uuid NOT NULL, "actorId" character varying, "actorName" character varying, "source" character varying NOT NULL DEFAULT 'bus', "happenedAt" TIMESTAMP NOT NULL DEFAULT now(), "data" jsonb, "requestId" character varying, "ip" character varying, "userAgent" character varying, CONSTRAINT "PK_481efbe8b0a403efe3f47a6528f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_cb1b54ade68f5b328a7befb456" ON "audit_event" ("actorId", "happenedAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_8362ebb0604780d58caf041675" ON "audit_event" ("aggregateType", "aggregateId") `);
        await queryRunner.query(`CREATE INDEX "IDX_07d0eb69576a8665fb43d8100a" ON "audit_event" ("type", "happenedAt") `);
        await queryRunner.query(`CREATE TABLE "service" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "createdById" uuid, "createdByName" character varying, "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedById" uuid, "updatedByName" character varying, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "key" character varying NOT NULL, "name" character varying NOT NULL, "description" character varying, "businessLineId" uuid NOT NULL, CONSTRAINT "PK_85a21558c006647cd76fdce044b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_eb06e01552141e2029286a93c2" ON "service" ("businessLineId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_1aeb70fe805c6b77ce65f2b2c1" ON "service" ("key") `);
        await queryRunner.query(`CREATE TABLE "request_template" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "createdById" uuid, "createdByName" character varying, "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedById" uuid, "updatedByName" character varying, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "serviceId" uuid NOT NULL, "key" character varying NOT NULL, "name" character varying NOT NULL, "jsonSchema" jsonb NOT NULL, "uiSchema" jsonb, "defaults" jsonb, "active" boolean NOT NULL DEFAULT true, "defaultAssignmentGroupId" uuid, "businessLineId" uuid NOT NULL, CONSTRAINT "PK_f15737f20d386267899203e214e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_10a79e5f6b2e1465c16206736e" ON "request_template" ("serviceId") `);
        await queryRunner.query(`CREATE INDEX "IDX_3f77d9ff288c8243f884924798" ON "request_template" ("businessLineId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_8545a69b87495a1468470bc5b7" ON "request_template" ("key") `);
        await queryRunner.query(`ALTER TABLE "membership" ADD CONSTRAINT "FK_eef2d9d9c70cd13bed868afedf4" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "membership" ADD CONSTRAINT "FK_8bc1674087575acecf0a648fc91" FOREIGN KEY ("groupId") REFERENCES "group"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "group" ADD CONSTRAINT "FK_c4ba7ec4945931d3ffab9724488" FOREIGN KEY ("businessLineId") REFERENCES "business_line"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_role" ADD CONSTRAINT "FK_ab40a6f0cd7d3ebfcce082131fd" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_role" ADD CONSTRAINT "FK_dba55ed826ef26b5b22bd39409b" FOREIGN KEY ("roleId") REFERENCES "role"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "group_role" ADD CONSTRAINT "FK_5f5e3b95cbdf0582623d98adf10" FOREIGN KEY ("groupId") REFERENCES "group"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "group_role" ADD CONSTRAINT "FK_e3fadd3be8dac5f5dcfe44551bc" FOREIGN KEY ("roleId") REFERENCES "role"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permission" ADD CONSTRAINT "FK_e3130a39c1e4a740d044e685730" FOREIGN KEY ("roleId") REFERENCES "role"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permission" ADD CONSTRAINT "FK_72e80be86cab0e93e67ed1a7a9a" FOREIGN KEY ("permissionId") REFERENCES "permission"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_permission" ADD CONSTRAINT "FK_deb59c09715314aed1866e18a81" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_permission" ADD CONSTRAINT "FK_a592f2df24c9d464afd71401ff6" FOREIGN KEY ("permissionId") REFERENCES "permission"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "case" ADD CONSTRAINT "FK_92817c50e333fe6e2ad1a0a7306" FOREIGN KEY ("requesterId") REFERENCES "user"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "case" ADD CONSTRAINT "FK_8907d0208936b6eae2951f5a72d" FOREIGN KEY ("assigneeId") REFERENCES "user"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "case" ADD CONSTRAINT "FK_6419fb53a5bec2b9f3722dabff2" FOREIGN KEY ("assignmentGroupId") REFERENCES "group"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "case" ADD CONSTRAINT "FK_9973cb8611f550ca336bdad4ac4" FOREIGN KEY ("businessLineId") REFERENCES "business_line"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "case_comment" ADD CONSTRAINT "FK_08907d0c3300311c19087aac217" FOREIGN KEY ("caseId") REFERENCES "case"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "case_link" ADD CONSTRAINT "FK_1a773d805281cba5adb9dccaae9" FOREIGN KEY ("caseId") REFERENCES "case"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "case_link" ADD CONSTRAINT "FK_d398b499b3bd5ca7a3e0c8d3922" FOREIGN KEY ("targetCaseId") REFERENCES "case"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "case_attachment" ADD CONSTRAINT "FK_f3e06f2721e46eea00824b311d1" FOREIGN KEY ("caseId") REFERENCES "case"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refresh_token" ADD CONSTRAINT "FK_8e913e288156c133999341156ad" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "token_blacklist" ADD CONSTRAINT "FK_cde27adb955c236798ccf3b9d5c" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sla_target" ADD CONSTRAINT "FK_7f6aa7deacb0e09d51f147c27f1" FOREIGN KEY ("businessLineId") REFERENCES "business_line"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sla_timer" ADD CONSTRAINT "FK_19c74fad2a0ac4ec41253baa033" FOREIGN KEY ("caseId") REFERENCES "case"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sla_timer" ADD CONSTRAINT "FK_d21e45bed4b3906ecf59fc6aefa" FOREIGN KEY ("targetId") REFERENCES "sla_target"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "email_channel" ADD CONSTRAINT "FK_16b07ef60f6bb9b05188518c1e2" FOREIGN KEY ("businessLineId") REFERENCES "business_line"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "email_inbound_state" ADD CONSTRAINT "FK_74b7832881f05a5b8376146db7c" FOREIGN KEY ("channelId") REFERENCES "email_channel"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "email_message" ADD CONSTRAINT "FK_907f61c9fef57870dd592b8f9bd" FOREIGN KEY ("channelId") REFERENCES "email_channel"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "email_message" ADD CONSTRAINT "FK_8322240cf857228a7f70746ad82" FOREIGN KEY ("caseId") REFERENCES "case"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "email_routing_rule" ADD CONSTRAINT "FK_e67071c18c96a0be0d8d1af8269" FOREIGN KEY ("businessLineId") REFERENCES "business_line"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "email_routing_rule" ADD CONSTRAINT "FK_d0b0b0535c0e79c20d859634e10" FOREIGN KEY ("channelId") REFERENCES "email_channel"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification_template" ADD CONSTRAINT "FK_679be42a80ce56e916a8465857f" FOREIGN KEY ("businessLineId") REFERENCES "business_line"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "service" ADD CONSTRAINT "FK_eb06e01552141e2029286a93c2d" FOREIGN KEY ("businessLineId") REFERENCES "business_line"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "request_template" ADD CONSTRAINT "FK_3f77d9ff288c8243f8849247980" FOREIGN KEY ("businessLineId") REFERENCES "business_line"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "request_template" DROP CONSTRAINT "FK_3f77d9ff288c8243f8849247980"`);
        await queryRunner.query(`ALTER TABLE "service" DROP CONSTRAINT "FK_eb06e01552141e2029286a93c2d"`);
        await queryRunner.query(`ALTER TABLE "notification_template" DROP CONSTRAINT "FK_679be42a80ce56e916a8465857f"`);
        await queryRunner.query(`ALTER TABLE "email_routing_rule" DROP CONSTRAINT "FK_d0b0b0535c0e79c20d859634e10"`);
        await queryRunner.query(`ALTER TABLE "email_routing_rule" DROP CONSTRAINT "FK_e67071c18c96a0be0d8d1af8269"`);
        await queryRunner.query(`ALTER TABLE "email_message" DROP CONSTRAINT "FK_8322240cf857228a7f70746ad82"`);
        await queryRunner.query(`ALTER TABLE "email_message" DROP CONSTRAINT "FK_907f61c9fef57870dd592b8f9bd"`);
        await queryRunner.query(`ALTER TABLE "email_inbound_state" DROP CONSTRAINT "FK_74b7832881f05a5b8376146db7c"`);
        await queryRunner.query(`ALTER TABLE "email_channel" DROP CONSTRAINT "FK_16b07ef60f6bb9b05188518c1e2"`);
        await queryRunner.query(`ALTER TABLE "sla_timer" DROP CONSTRAINT "FK_d21e45bed4b3906ecf59fc6aefa"`);
        await queryRunner.query(`ALTER TABLE "sla_timer" DROP CONSTRAINT "FK_19c74fad2a0ac4ec41253baa033"`);
        await queryRunner.query(`ALTER TABLE "sla_target" DROP CONSTRAINT "FK_7f6aa7deacb0e09d51f147c27f1"`);
        await queryRunner.query(`ALTER TABLE "token_blacklist" DROP CONSTRAINT "FK_cde27adb955c236798ccf3b9d5c"`);
        await queryRunner.query(`ALTER TABLE "refresh_token" DROP CONSTRAINT "FK_8e913e288156c133999341156ad"`);
        await queryRunner.query(`ALTER TABLE "case_attachment" DROP CONSTRAINT "FK_f3e06f2721e46eea00824b311d1"`);
        await queryRunner.query(`ALTER TABLE "case_link" DROP CONSTRAINT "FK_d398b499b3bd5ca7a3e0c8d3922"`);
        await queryRunner.query(`ALTER TABLE "case_link" DROP CONSTRAINT "FK_1a773d805281cba5adb9dccaae9"`);
        await queryRunner.query(`ALTER TABLE "case_comment" DROP CONSTRAINT "FK_08907d0c3300311c19087aac217"`);
        await queryRunner.query(`ALTER TABLE "case" DROP CONSTRAINT "FK_9973cb8611f550ca336bdad4ac4"`);
        await queryRunner.query(`ALTER TABLE "case" DROP CONSTRAINT "FK_6419fb53a5bec2b9f3722dabff2"`);
        await queryRunner.query(`ALTER TABLE "case" DROP CONSTRAINT "FK_8907d0208936b6eae2951f5a72d"`);
        await queryRunner.query(`ALTER TABLE "case" DROP CONSTRAINT "FK_92817c50e333fe6e2ad1a0a7306"`);
        await queryRunner.query(`ALTER TABLE "user_permission" DROP CONSTRAINT "FK_a592f2df24c9d464afd71401ff6"`);
        await queryRunner.query(`ALTER TABLE "user_permission" DROP CONSTRAINT "FK_deb59c09715314aed1866e18a81"`);
        await queryRunner.query(`ALTER TABLE "role_permission" DROP CONSTRAINT "FK_72e80be86cab0e93e67ed1a7a9a"`);
        await queryRunner.query(`ALTER TABLE "role_permission" DROP CONSTRAINT "FK_e3130a39c1e4a740d044e685730"`);
        await queryRunner.query(`ALTER TABLE "group_role" DROP CONSTRAINT "FK_e3fadd3be8dac5f5dcfe44551bc"`);
        await queryRunner.query(`ALTER TABLE "group_role" DROP CONSTRAINT "FK_5f5e3b95cbdf0582623d98adf10"`);
        await queryRunner.query(`ALTER TABLE "user_role" DROP CONSTRAINT "FK_dba55ed826ef26b5b22bd39409b"`);
        await queryRunner.query(`ALTER TABLE "user_role" DROP CONSTRAINT "FK_ab40a6f0cd7d3ebfcce082131fd"`);
        await queryRunner.query(`ALTER TABLE "group" DROP CONSTRAINT "FK_c4ba7ec4945931d3ffab9724488"`);
        await queryRunner.query(`ALTER TABLE "membership" DROP CONSTRAINT "FK_8bc1674087575acecf0a648fc91"`);
        await queryRunner.query(`ALTER TABLE "membership" DROP CONSTRAINT "FK_eef2d9d9c70cd13bed868afedf4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8545a69b87495a1468470bc5b7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3f77d9ff288c8243f884924798"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_10a79e5f6b2e1465c16206736e"`);
        await queryRunner.query(`DROP TABLE "request_template"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1aeb70fe805c6b77ce65f2b2c1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_eb06e01552141e2029286a93c2"`);
        await queryRunner.query(`DROP TABLE "service"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_07d0eb69576a8665fb43d8100a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8362ebb0604780d58caf041675"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cb1b54ade68f5b328a7befb456"`);
        await queryRunner.query(`DROP TABLE "audit_event"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ffdbbd32062ba09e2aebe72d00"`);
        await queryRunner.query(`DROP TABLE "notification_template"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e67071c18c96a0be0d8d1af826"`);
        await queryRunner.query(`DROP TABLE "email_routing_rule"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a73d83b3021f6d56a57965adf3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8322240cf857228a7f70746ad8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_907f61c9fef57870dd592b8f9b"`);
        await queryRunner.query(`DROP TABLE "email_message"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_74b7832881f05a5b8376146db7"`);
        await queryRunner.query(`DROP TABLE "email_inbound_state"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c110b35ab63da1889e49127a9a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_16b07ef60f6bb9b05188518c1e"`);
        await queryRunner.query(`DROP TABLE "email_channel"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f3e3ceaee9e1f40d91736b24c1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d21e45bed4b3906ecf59fc6aef"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_19c74fad2a0ac4ec41253baa03"`);
        await queryRunner.query(`DROP TABLE "sla_timer"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_735b920a4e967f99beb36d8c0d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7f6aa7deacb0e09d51f147c27f"`);
        await queryRunner.query(`DROP TABLE "sla_target"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_73e5965ffdbd4a9f2de7c93043"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1cebed586d3a7c46f3f9b76cf1"`);
        await queryRunner.query(`DROP TABLE "token_blacklist"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c31d0a2f38e6e99110df62ab0a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_aa5d23e946f1e4dc31a57ee1a5"`);
        await queryRunner.query(`DROP TABLE "refresh_token"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f3e06f2721e46eea00824b311d"`);
        await queryRunner.query(`DROP TABLE "case_attachment"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1a773d805281cba5adb9dccaae"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d398b499b3bd5ca7a3e0c8d392"`);
        await queryRunner.query(`DROP TABLE "case_link"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2d415c0c1a476a32e1958e1738"`);
        await queryRunner.query(`DROP TABLE "case_comment"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8cf7d3e75b7dd1eced77de0f14"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9973cb8611f550ca336bdad4ac"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6419fb53a5bec2b9f3722dabff"`);
        await queryRunner.query(`DROP TABLE "case"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1cf6c7f47d0655afa389e1bd59"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_deb59c09715314aed1866e18a8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a592f2df24c9d464afd71401ff"`);
        await queryRunner.query(`DROP TABLE "user_permission"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b42bbacb8402c353df82243254"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e3130a39c1e4a740d044e68573"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_72e80be86cab0e93e67ed1a7a9"`);
        await queryRunner.query(`DROP TABLE "role_permission"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_20ff45fefbd3a7c04d2572c3bb"`);
        await queryRunner.query(`DROP TABLE "permission"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4ae7c04176fcfe3a6aef3f368b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5f5e3b95cbdf0582623d98adf1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e3fadd3be8dac5f5dcfe44551b"`);
        await queryRunner.query(`DROP TABLE "group_role"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7b4e17a669299579dfa55a3fc3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ab40a6f0cd7d3ebfcce082131f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dba55ed826ef26b5b22bd39409"`);
        await queryRunner.query(`DROP TABLE "user_role"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_128d7c8c9af53479d0b9e00eb5"`);
        await queryRunner.query(`DROP TABLE "role"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b2177905daa1bf150e743072d3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c4ba7ec4945931d3ffab972448"`);
        await queryRunner.query(`DROP TABLE "group"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f81f7f3398bd7c979dd3b59deb"`);
        await queryRunner.query(`DROP TABLE "business_line"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9c7d697a4844cf8b931988b24f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_eef2d9d9c70cd13bed868afedf"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8bc1674087575acecf0a648fc9"`);
        await queryRunner.query(`DROP TABLE "membership"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_78a916df40e02a9deb1c4b75ed"`);
        await queryRunner.query(`DROP TABLE "user"`);
    }

}
