export enum EmailProtocolEnum {
  SMTP = 'SMTP',
  IMAP = 'IMAP',
  POP3 = 'POP3',
}

export enum NotificationTypeEnum {
  INCIDENT_CREATED = 'INCIDENT_CREATED',
  INCIDENT_UPDATED = 'INCIDENT_UPDATED',
  INCIDENT_RESOLVED = 'INCIDENT_RESOLVED',
  SERVICE_REQUEST_CREATED = 'SERVICE_REQUEST_CREATED',
  SERVICE_REQUEST_APPROVED = 'SERVICE_REQUEST_APPROVED',
  SERVICE_REQUEST_REJECTED = 'SERVICE_REQUEST_REJECTED',
  USER_CREATED = 'USER_CREATED',
  SYSTEM_ALERT = 'SYSTEM_ALERT',
  LDAP_SYNC_STATUS = 'LDAP_SYNC_STATUS',
}

export enum EmailTemplateTypeEnum {
  INCIDENT_NOTIFICATION = 'INCIDENT_NOTIFICATION',
  SERVICE_REQUEST_NOTIFICATION = 'SERVICE_REQUEST_NOTIFICATION',
  USER_WELCOME = 'USER_WELCOME',
  PASSWORD_RESET = 'PASSWORD_RESET',
  SYSTEM_MAINTENANCE = 'SYSTEM_MAINTENANCE',
}

export enum EmailQueueStatusEnum {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  SENT = 'SENT',
  FAILED = 'FAILED',
  RETRYING = 'RETRYING',
  CANCELLED = 'CANCELLED',
}

export enum EmailPriorityEnum {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
} 